### ISSUE TITLE
Crash while constructing 

### ISSUE THREAD

**Issue by MatthewSandman** [Daveyx0/MultiMob#19]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  LoadingPlugin (Quark-r1.5-145.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 2/5/19 8:27 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:415)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:286)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:271)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:256)
	at net.minecraftforge.common.util.EnumHelper.addSpawnPlacementType(EnumHelper.java:156)
	at net.daveyx0.multimob.core.MultiMob.<clinit>(MultiMob.java:50)
	... 38 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.common.util.EnumHelper.getConstructorAccessor(EnumHelper.java:207)
	at net.minecraftforge.common.util.EnumHelper.makeEnum(EnumHelper.java:220)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:406)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1103733312 bytes (1052 MB) / 1610612736 bytes (1536 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                              | Signature                                |
	|:----- |:-------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft            | 1.12.2                   | minecraft.jar                                       | None                                     |
	| UC    | mcp                  | 9.42                     | minecraft.jar                                       | None                                     |
	| UC    | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | openmodscore         | 0.12                     | minecraft.jar                                       | None                                     |
	| UC    | obfuscate            | 0.2.6                    | minecraft.jar                                       | None                                     |
	| UC    | actuallyadditions    | 1.12.2-r144              | ActuallyAdditions-1.12.2-r144.jar                   | None                                     |
	| UC    | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UC    | actuallybaubles      | 1.1                      | ActuallyBaubles-1.12-1.1.jar                        | None                                     |
	| UC    | advancedcombat       | 1.1.2                    | advancedcombat-1.1.2-[1.12].jar                     | None                                     |
	| UC    | extrautils2          | 1.0                      | extrautils2-1.12-1.9.8.jar                          | None                                     |
	| UC    | flyringbaublemod     | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar         | None                                     |
	| UC    | jei                  | 4.14.4.263               | jei_1.12.2-4.14.4.263.jar                           | None                                     |
	| UC    | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| UC    | aroma1997core        | 2.0.0.0.b162             | Aroma1997Core-1.12.2-2.0.0.0.b162.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UC    | aroma1997sdimension  | 2.0.0.2.b87              | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b87.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UC    | attributefix         | 1.0.7                    | AttributeFix-1.12.2-1.0.7.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | quark                | r1.5-145                 | Quark-r1.5-145.jar                                  | None                                     |
	| UC    | autoreglib           | 1.3-21                   | AutoRegLib-1.3-21.jar                               | None                                     |
	| UC    | baublelicious        | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                           | None                                     |
	| UC    | baubleofundying      | 1.0.1                    | BaubleOfUndying-1.12-1.0.1.jar                      | None                                     |
	| UC    | betteranimals        | 3.1                      | betteranimals-4.0.jar                               | None                                     |
	| UC    | betteranimalsplus    | 4.1.0                    | betteranimalsplus-4.1.0.jar                         | None                                     |
	| UC    | betterbedrockgen     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar               | None                                     |
	| UC    | biomesoplenty        | 7.0.1.2424               | BiomesOPlenty-1.12.2-7.0.1.2424-universal.jar       | None                                     |
	| UC    | bonsaitrees          | 1.0.5                    | bonsaitrees-1.0.5-b77.jar                           | None                                     |
	| UC    | bookshelf            | 2.3.569                  | Bookshelf-1.12.2-2.3.569.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | brownmooshrooms      | 1.0.0                    | brownmooshrooms-1.0.0.jar                           | None                                     |
	| UC    | buildinggadgets      | 2.6.0                    | BuildingGadgets-2.6.0.jar                           | None                                     |
	| UC    | cfm                  | 5.10.0                   | cfm-5.10.0-mc1.12.2.jar                             | None                                     |
	| UC    | clumps               | 3.1.1                    | Clumps-3.1.1.jar                                    | None                                     |
	| UC    | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | colytra              | 1.1.0.2                  | colytra-1.12.2-1.1.0.2.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | craftstudioapi       | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar               | None                                     |
	| UC    | ctm                  | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                           | None                                     |
	| UC    | customspawner        | 3.11.4                   | CustomMobSpawner-3.11.4.jar                         | None                                     |
	| UC    | cyclicmagic          | 1.17.16                  | Cyclic-1.12.2-1.17.16.jar                           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| UC    | orespawn             | 3.3.0                    | OreSpawn-1.12-3.3.0.155.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | densemetals          | 1.2.0                    | DenseMetals-1.12-1.2.0.21.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | dynamictrees         | 1.12.2-0.9.4             | DynamicTrees-1.12.2-0.9.4.jar                       | None                                     |
	| UC    | dynamictreesbop      | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar                   | None                                     |
	| UC    | harvestcraft         | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                     | None                                     |
	| UC    | dynamictreesphc      | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                    | None                                     |
	| UC    | eerieentities        | 1.0.6                    | EerieEntities-1.12.2-1.0.6.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | elderarsenal         | 1.6.0                    | ElderArsenal-1.12.2-1.6.0.jar                       | None                                     |
	| UC    | eplus                | 5.0.174                  | EnchantingPlus-1.12.2-5.0.174.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | csb_ench_table       | 1.1.3                    | EnchantingTable-1.12-1.1.3.jar                      | None                                     |
	| UC    | enchdesc             | 1.1.13                   | EnchantmentDescriptions-1.12.2-1.1.13.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                               | None                                     |
	| UC    | fencejumper          | 1.0.5                    | fencejumper-1.12-1.0.5.jar                          | None                                     |
	| UC    | forgelin             | 1.8.2                    | Forgelin-1.8.2.jar                                  | None                                     |
	| UC    | ichunutil            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
	| UC    | hats                 | 7.0.0                    | Hats-1.12.2-7.0.2.jar                               | None                                     |
	| UC    | heroicarmory         | 1.1.3                    | heroicarmory-1.2.0.jar                              | None                                     |
	| UC    | hexlands             | 1.8.1                    | hexlands-1.8.1.jar                                  | None                                     |
	| UC    | infinity             | 0.13.2                   | Infinity-0.13.2.jar                                 | None                                     |
	| UC    | mantle               | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                            | None                                     |
	| UC    | inspirations         | 1.12.2-0.2.3             | Inspirations-1.12.2-0.2.3.jar                       | None                                     |
	| UC    | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest            | 1.12.2-7.0.58.841        | ironchest-1.12.2-7.0.58.841.jar                     | None                                     |
	| UC    | jehc                 | 1.12.2                   | JEHC-1.12.2-1.6.1.0.jar                             | None                                     |
	| UC    | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                         | None                                     |
	| UC    | jeresources          | 0.8.10.50                | JustEnoughResources-1.12.2-0.8.10.50.jar            | None                                     |
	| UC    | metalchests          | v4.0.1.g01955d6          | MetalChests-v4.0.1.g01955d6.jar                     | None                                     |
	| UC    | moreoverlays         | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                      | None                                     |
	| UC    | llibrary             | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                          | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | mowziesmobs          | 1.5.1                    | mowziesmobs-1.5.1.jar                               | None                                     |
	| U     | multimob             | 1.0.5                    | multimob-1.0.5.jar                                  | None                                     |
	| U     | naturescompass       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                     | None                                     |
	| U     | nethergoldore        | 1.2.1                    | nethergoldore-1.2.1-mc1.12.x.jar                    | None                                     |
	| U     | recipehandler        | 0.12                     | NoMoreRecipeConflict-0.12(1.12.2).jar               | None                                     |
	| U     | openmods             | 0.12                     | OpenModsLib-1.12.2-0.12.jar                         | None                                     |
	| U     | openblocks           | 1.8                      | OpenBlocks-1.12.2-1.8.jar                           | None                                     |
	| U     | oreexcavation        | 1.4.133                  | OreExcavation-1.4.133.jar                           | None                                     |
	| U     | parry                | 1.0                      | parry-1.0-hotfix.jar                                | None                                     |
	| U     | placeableitems       | 3.3                      | placeableitems-3.3.jar                              | None                                     |
	| U     | prefab               | 1.3.0.26                 | prefab-1.3.0.26.jar                                 | None                                     |
	| U     | primitivemobs        | 1.2.3a                   | primitivemobs-1.2.3a.jar                            | None                                     |
	| U     | quarkoddities        | 1                        | QuarkOddities-1.12.2.jar                            | None                                     |
	| U     | radixcore            | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar                | None                                     |
	| U     | randomthings         | 4.2.4                    | RandomThings-MC1.12.2-4.2.4.jar                     | None                                     |
	| U     | xreliquary           | 1.12.2-1.3.4.780         | Reliquary-1.12.2-1.3.4.780.jar                      | None                                     |
	| U     | additionalstructures | 2.0.1                    | Rex's-Additional-Structures-1.12.x+-(v.2.1.0).jar   | None                                     |
	| U     | rustic               | 1.0.15                   | rustic-1.0.15.jar                                   | None                                     |
	| U     | rusticbopwoods       | 1.0                      | rusticbopwoods-1.0.jar                              | None                                     |
	| U     | scannable            | 1.6.3.22                 | Scannable-MC1.12.2-1.6.3.22.jar                     | None                                     |
	| U     | sereneseasons        | 1.2.15                   | SereneSeasons-1.12.2-1.2.15-universal.jar           | None                                     |
	| U     | sophisticatedwolves  | 3.13.7                   | SophisticatedWolves-1.12.2-3.13.7.jar               | None                                     |
	| U     | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                | None                                     |
	| U     | theoneprobe          | 1.4.27                   | theoneprobe-1.12-1.4.27.jar                         | None                                     |
	| U     | tp                   | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar          | None                                     |
	| U     | ts2k16               | 1.2.8                    | Twerk-Sim-Mod-1.12.2.jar                            | None                                     |
	| U     | walljump             | 1.12.2-1.2.1             | walljump-1.12.2-1.2.1.jar                           | None                                     |
	| U     | worleycaves          | 1.3.0                    | worleycaves-1.3.0.jar                               | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.1.0.2.jar)
  c4.colytra.asm.ElytraTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
  lumien.randomthings.asm.ClassTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.8.2.jar)
  
LoadingPlugin (Quark-r1.5-145.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 550 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- TheOneProbePlugin (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 550 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Wild+Dragons.zip, Wild+Hippocampi.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU E6500 @ 2.93GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTX 550 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Daveyx0** [comment]
Sorry for the late response! Updating optifine to OptiFine 1.12.2 HD U E3. Should fix this!
