### ISSUE TITLE
Game Crash before starting

### ISSUE THREAD

**Issue by bailudayo** [Daveyx0/MultiMob#28]
I created a modpack with a lot of mods, they work and have no problem, except Primitive Mobs crashing/MultiMob crashing. I don't know which mod causes the crash, without these two they work perfectly.

Here is the crash report

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 4/13/19 2:34 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:418)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:289)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:274)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:259)
	at net.minecraftforge.common.util.EnumHelper.addSpawnPlacementType(EnumHelper.java:159)
	at net.daveyx0.multimob.core.MultiMob.<clinit>(MultiMob.java:50)
	... 38 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.entity.EntityLiving$SpawnPlacementType.<init>(java.lang.String, int, java.util.function.BiPredicate)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at net.minecraftforge.common.util.EnumHelper.getConstructorAccessor(EnumHelper.java:210)
	at net.minecraftforge.common.util.EnumHelper.makeEnum(EnumHelper.java:223)
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:409)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 413497440 bytes (394 MB) / 1485307904 bytes (1416 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 Optifine OptiFine_1.12.2_HD_U_C6 110 mods loaded, 110 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                             | Signature                                |
	|:----- |:------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                 | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LC    | mcp                       | 9.42                     | minecraft.jar                                      | None                                     |
	| LC    | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                     | 14.23.5.2823             | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | movillages                | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                         | None                                     |
	| LC    | ic2                       | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | advanced_machines         | 61.0.1                   | Advanced Machines-61.0.1.jar                       | None                                     |
	| LC    | orbis-lib                 | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build42.jar                 | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | aether                    | 0.2.0                    | aether_ii-1.12.2-0.2.0+build42-universal.jar       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | infinitylib               | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                             | None                                     |
	| LC    | agricraft                 | 2.12.0-1.12.0-a6         | AgriCraft-2.12.0-1.12.0-a6.jar                     | None                                     |
	| LC    | ambientsounds             | 3.0                      | AmbientSounds_v3.0.3_mc1.12.2.jar                  | None                                     |
	| LC    | antiqueatlas              | 4.5.0                    | antiqueatlas-1.12.2-4.5.0.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LC    | antiqueatlasoverlay       | 1.2                      | antiqueatlas-1.12.2-4.5.0.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LC    | appliedenergistics2       | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | atlasextras               | 1.6                      | AtlasExtras-1.12.2-1.6.jar                         | None                                     |
	| LC    | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LC    | quark                     | r1.5-146                 | Quark-r1.5-146.jar                                 | None                                     |
	| LC    | autoreglib                | 1.3-26                   | AutoRegLib-1.3-26.jar                              | None                                     |
	| LC    | backpack                  | 3.0.2                    | backpack-3.0.2-1.12.2.jar                          | None                                     |
	| LC    | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | bdlib                     | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LC    | betaplus                  | 0.4back                  | betaplus-0.4.1.jar                                 | None                                     |
	| LC    | betterquesting            | 3.5.296                  | BetterQuesting-3.5.296.jar                         | None                                     |
	| LC    | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LC    | buildcraftlib             | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftcore            | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftenergy          | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | forestry                  | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| LC    | binniecore                | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | binniedesign              | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | genetics                  | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | botany                    | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | extrabees                 | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | extratrees                | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                   | None                                     |
	| LC    | botania                   | r1.10-360                | Botania r1.10-360.jar                              | None                                     |
	| LC    | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | brandonscore              | 2.4.9                    | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
	| LC    | buildcraftbuilders        | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcrafttransport       | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftsilicon         | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftcompat          | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftfactory         | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | buildcraftrobotics        | 7.99.23                  | buildcraft-all-7.99.23.jar                         | None                                     |
	| LC    | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LC    | chesttransporter          | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
	| LC    | chiselsandbits            | 14.31                    | chiselsandbits-14.31.jar                           | None                                     |
	| LC    | sanlib                    | 1.5.1                    | SanLib-1.12.2-1.5.1.jar                            | df48348748b5e141b1d118e2302a8d5be930b708 |
	| LC    | claysoldiers              | 3.0.0-beta.2             | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar            | None                                     |
	| LC    | cofhcore                  | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
	| LC    | cofhworld                 | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalfoundation         | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | draconicevolution         | 2.3.20                   | Draconic-Evolution-1.12.2-2.3.20.333-universal.jar | None                                     |
	| LC    | mocreatures               | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
	| LC    | erebus                    | 1.0.29                   | Erebus-1.0.29.jar                                  | None                                     |
	| LC    | mantle                    | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                           | None                                     |
	| LC    | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| LC    | tconstruct                | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                   | None                                     |
	| LC    | extrautils2               | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | foodexpansion             | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                      | None                                     |
	| LC    | forgelin                  | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
	| LC    | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| LC    | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
	| LC    | fpsreducer                | mc1.12.2-1.10.3          | FpsReducer-mc1.12.2-1.10.3.jar                     | None                                     |
	| LC    | gendustry                 | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                     | None                                     |
	| LC    | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | llibrary                  | 1.7.18                   | llibrary-1.7.18-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire                | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                        | None                                     |
	| LC    | ichunutil                 | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mekanism                  | 1.12.2-9.6.7.360         | Mekanism-1.12.2-9.6.7.360.jar                      | None                                     |
	| LC    | teslacorelib              | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.11-235.jar         | None                                     |
	| LC    | integrationforegoing      | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LC    | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                 | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| LC    | journeymap                | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LC    | lootbags                  | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                        | None                                     |
	| LC    | morph                     | 7.1.3                    | Morph-1.12.2-7.1.3.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mowziesmobs               | 1.5.3                    | mowziesmobs-1.5.3.jar                              | None                                     |
	| LC    | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar            | None                                     |
	| L     | multimob                  | 1.0.5                    | multimob-1.0.5.jar                                 | None                                     |
	| L     | netherendingores          | 1.12.2-1.3               | Netherending-Ores-1.12.2-1.3.jar                   | None                                     |
	| L     | portalgun                 | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                         | None                                     |
	| L     | primitivemobs             | 1.2.3a                   | primitivemobs-1.2.3a.jar                           | None                                     |
	| L     | projecte                  | 1.12.2-PE1.4.0           | ProjectE-1.12.2-PE1.4.0.jar                        | None                                     |
	| L     | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                | None                                     |
	| L     | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar              | None                                     |
	| L     | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| L     | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar         | None                                     |
	| L     | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar         | None                                     |
	| L     | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar            | None                                     |
	| L     | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| L     | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| L     | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar          | None                                     |
	| L     | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar               | None                                     |
	| L     | refinedstorage            | 1.6.14                   | refinedstorage-1.6.14.jar                          | None                                     |
	| L     | sanplayermodel            | 1.1.1                    | SanLib-1.12.2-1.5.1.jar                            | None                                     |
	| L     | solarflux                 | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                   | None                                     |
	| L     | bq_standard               | 3.4.154                  | StandardExpansion-3.4.154.jar                      | None                                     |
	| L     | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| L     | thermalexpansion          | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | None                                     |
	| L     | thermaldynamics           | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | None                                     |
	| L     | treechopper               | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| L     | tropicraft                | 7.1.8.105                | tropicraft-MC1.12.2-7.1.8.105.jar                  | None                                     |
	| L     | wailaharvestability       | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| L     | phosphor-lighting         | 1.12.2-0.1.6             | phosphor-1.12.2-0.1.6+build31.jar                  | None                                     |
	| L     | thebetweenlands           | 3.4.6                    | TheBetweenlands-3.4.6-universal.jar                | None                                     |
	| L     | teslacorelib_registries   | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTS 450/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2823
	LWJGL: 2.9.4
	OpenGL: GeForce GTS 450/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E6750 @ 2.66GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GTS 450/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2`

**Comment by metapuns** [comment]
I had the exact same problem but I just read another thread on here and for me and them it was Optifine. I just replaced mine and Mowzie's and Primitive Mobs works now.
