### ISSUE TITLE
java.lang.NullPointerException in server tick loop

### ISSUE THREAD

**Issue by bluelightning32** [Daveyx0/MultiMob#9]
My server is running MultiMob version 1.0.4 as part of the Dimension Zero modpack, version 5.4.

The server was running fine, then it crashed with this exception:
```
java.lang.NullPointerException: Exception in server tick loop
        at net.daveyx0.multimob.spawn.MMWorldSpawner.findChunksForSpawning(MMWorldSpawner.java:184)
        at net.daveyx0.multimob.spawn.MMSpawnerEventHandler.onWorldTickEvent(MMSpawnerEventHandler.java:44)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1626_MMSpawnerEventHandler_onWorldTickEvent_WorldTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

Full crash report: https://gist.github.com/bluelightning32/e2ae57b75dfcde263e54015fd9427630

The server restarted, and it crashed again with the same error. It restarted one more time, but didn't crash.

**Comment by Daveyx0** [comment]
Hmm this is strange; this should not happen. Anyway i added a safety null check there for the next update which should fix the issue. :)

**Comment by SirAron111** [comment]
O my another problem someone else posted me this error just now so I came to check but blue already posted it if you need information on settings or anything that are in use I can send you the config files or so.

**Comment by Daveyx0** [comment]
In 1.0.4a this should not happen. Let me know if it still does somehow.
